classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- cluster.rverchikov-vlab
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: https://github.com/Mirantis/mk-lab-salt-model.git
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        infra_compute_node01:
          params:
            keepalived_vip_priority: 100
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_compute_node01:
          name: ${_param:openstack_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node01_control_address}
            single_address: ${_param:openstack_compute_node01_single_address}
            tenant_address: ${_param:openstack_compute_node01_tenant_address}
