classes:

- system.linux.system.repo.mos9

- system.linux.system.repo.saltstack_2016_3_trusty
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.glusterfs.server.cluster
- system.salt.control.virt
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- cluster.rverchikov-vlab
parameters:
  _param:
    cluster_vip_address: ${_param:infra_compute_address}
    cluster_node01_address: ${_param:infra_compute_node01_address}
    cluster_node02_address: ${_param:infra_compute_node02_address}
    cluster_node03_address: ${_param:infra_compute_node03_address}
    keepalived_vip_interface: ens4
    keepalived_vip_virtual_router_id: 69
  salt:
    control:
      size:
      # Default production sizing
        openstack.control:
          cpu: 4
          ram: 8192
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        openstack.proxy:
          cpu: 2
          ram: 2048
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        opencontrail.analytics:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: default
      cluster:
        internal:
          node:
            prx02:
              provider: kvm03.${_param:cluster_domain}
#FIXME - done
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: manual
        ens4:
          enabled: true
          type: eth
          proto: manual
        ens5:
          enabled: true
          type: eth
          proto: manual
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: 255.255.255.0
          use_interfaces:
          - ens3
        bond0:
          enabled: true
          proto: manual
          type: bond
          use_interfaces:
          - ens4
          - ens5
          slaves: ens4 ens5
          mode: active-backup
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          gateway: 10.167.4.1
          netmask: 255.255.255.0
          name_servers:
          - 8.8.8.8
          - 8.8.4.4
          use_interfaces:
          - bond0
